# vim: syntax=ruby filetype=ruby

tap 'homebrew/bundle'
tap 'homebrew/core'
tap 'weaveworks/tap'
tap 'adoptopenjdk/openjdk'
tap 'azure/draft'
tap 'homebrew/cask'

# System tools
brew 'gettext'
brew 'proctools'
brew 'pstree'
brew 'coreutils'
brew 'findutils'
brew 'htop'
brew 'gnu-tar'
brew 'gnu-which'
brew 'gnu-sed'
brew 'gnu-indent'
brew 'grep'
brew 'gawk'
brew 'gnutls'
brew 'gnu-getopt'
brew 'parallel'
brew 'screen'
brew 'ncurses'
brew 'pv'
brew 'unrar'
brew 'shfmt'
brew 'sleepwatcher'

# Development & Power Tools
cask 'iterm2'
cask 'visual-studio-code'
brew 'bash'
brew 'bash-completion@2'
brew 'zsh'
brew 'zsh-syntax-highlighting'
brew 'zsh-autosuggestions'
brew 'zsh-completions'
brew 'ack'
brew 'ccat'
brew 'diff-so-fancy'
brew 'git' # no force-bottle: git --exec-path doesn't work, remote helpers missing from path
brew 'gti'
brew 'go'
brew 'fzf'
brew 'grv'
brew 'hub'
brew 'jq'
brew 'node'
# brew 'rust'
brew 'libyaml'
brew 'ruby'
# brew 'python2'
# brew 'python3'
brew 'python'
brew 'openssl'
brew 'ldns'
brew 'openssh'
brew 'protobuf'
brew 'prototool'
brew 'the_silver_searcher'
brew 'ripgrep'
brew 'tree'
brew 'wget'
cask 'google-cloud-sdk'
brew 'watch'
brew 'fd'
brew 'ncdu'
brew 'wdiff'
brew 'entr'
brew 'bats'
brew 'tldr'
brew 'shellcheck'
brew 'telnet'
brew 'mitmproxy'
brew 'fortio'
brew 'gdb'

brew 'jenv'

cask 'adoptopenjdk'
cask 'adoptopenjdk11'
cask 'jetbrains-toolbox'
cask 'sourcetree'
brew 'maven'
brew 'azure/draft/draft'
# brew 'bazelbuild/tap/bazel'
brew 'bazel'
brew 'autoconf'
brew 'automake'
brew 'cmake'
brew 'ninja'
brew 'libtool'
brew 'gcc'
brew 'grpcurl'

# Commit signing
brew 'pinentry-mac'
brew 'gnupg'
brew 'gpg2'

# Containers
brew 'kubernetes-cli'
# brew 'openshift-cli'
brew 'kubernetes-helm'
brew 'kubectx'
brew 'kube-ps1'
brew 'minikube'
brew 'docker-machine-driver-hyperkit'
brew 'skaffold'
brew 'kustomize'
brew 'cfssl'
# cask 'docker' # docker for desktop
brew 'awscli'
brew 'weaveworks/tap/eksctl'
brew 'azure-cli'

# Fun tools
brew 'asciinema'
brew 'lolcat'

# kubernetes dev
brew 'hg'
brew 'etcd'

# Desktop Software
cask 'zoomus'
cask 'flux'
cask 'slack'
cask 'spectacle'
cask '1password'
cask 'dropbox'
cask 'google-chrome'
cask 'istat-menus'
cask 'grammarly'
cask 'cleanmymac'
cask 'chai'
